server:
  port: 9093
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
spring:
  cloud:
    gateway:
      routes:
      - id: userloginNewsApp
        uri: lb://userloginNewsApp
        predicates:
        - Path=/api/v1/user/**
      - id: newsdetails
        uri: lb://newsdetails
        predicates:
        - Path=/api/v1/news/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
